### ISSUE TITLE
naming suggestions

### ISSUE THREAD

**Issue by max-mapper** [nodeschool/iran#1]
Welcome!

The name `nodeschool/iranian-node` is a little long, you might consider naming it simply `nodeschool/iran` or even naming it after the specific city that you will be organizing in, for example `nodeschool/tehran`. Most of our chapters are named after the city that they are in, and not the country.

**Comment by hrayatnia** [comment]
ok sure

**Comment by jasonrhodes** [comment]
When you get this city/name thing figured out, can you submit a PR to the nodeschool/nodeschool.github.io repo and add a chapter JSON file to the /chapters directory?

Explanation here: https://github.com/nodeschool/organizers/blob/master/README.md#5

**Comment by hrayatnia** [comment]
sure

**Comment by hrayatnia** [comment]
sorry but The workshop will be held in 3 cities
babol,mazandaran----> Noshirvani institute technology
sari,mazandaran ---> national park of technology
tehran,tehran --->iran university of science and technology
but i submit one city :-S 
will be any problem occur?
@jasonrhodes

**Comment by behrad** [comment]
سلام @hrayatnia 
I was trying to begin a nodeschool/tehran that I found this, happy to see you've been starting this movement in 3 cities.

Can we have a private talk about this?

**Comment by hrayatnia** [comment]
@behrad درود  sure

**Comment by behrad** [comment]
I dropped you an email @hrayatnia please reply me with your contact information
